# Generated by Django 4.1.7 on 2023-07-20 17:30

import datetime
import django.core.validators
from django.db import migrations, models
import racer.utils


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Passage',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('title', models.CharField(max_length=200)),
                ('text', models.TextField(validators=[racer.utils.noInvalidSpaces, django.core.validators.MinLengthValidator(100, message='Passage must have atleast 100 charexters.')])),
                ('difficulty', models.PositiveIntegerField(validators=[django.core.validators.MaxValueValidator(3, message='Difficulty must be between 0 and 3.'), django.core.validators.MinValueValidator(0, message='Difficulty must be between 0 and 3.')])),
                ('averageTime', models.DurationField(default=datetime.timedelta(0))),
                ('totalTries', models.PositiveIntegerField(default=0)),
            ],
        ),
    ]
