# Generated by Django 4.1.7 on 2023-07-21 14:14

import django.core.validators
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('multi_mode', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='lobby',
            name='difficulty',
            field=models.PositiveIntegerField(validators=[django.core.validators.MaxValueValidator(2, message='Difficulty can not be more than 2')]),
        ),
        migrations.AlterField(
            model_name='lobby',
            name='playerCount',
            field=models.PositiveIntegerField(validators=[django.core.validators.MaxValueValidator(5, message='There can only be 5 player at max in a lobby.')]),
        ),
    ]
