# Generated by Django 4.1.7 on 2023-07-21 14:52

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('multi_mode', '0003_player'),
    ]

    operations = [
        migrations.CreateModel(
            name='PlayerProgress',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('wpm', models.PositiveIntegerField()),
                ('progress', models.PositiveIntegerField()),
                ('lobby', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='multi_mode.lobby')),
                ('player', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='multi_mode.player')),
            ],
        ),
    ]
