# Generated by Django 4.1.7 on 2023-07-21 14:53

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('multi_mode', '0004_playerprogress'),
    ]

    operations = [
        migrations.AddField(
            model_name='playerprogress',
            name='accuracy',
            field=models.PositiveIntegerField(default=100),
        ),
    ]
