# Generated by Django 4.1.7 on 2023-07-21 15:10

from django.db import migrations, models
import multi_mode.models


class Migration(migrations.Migration):

    dependencies = [
        ('multi_mode', '0005_playerprogress_accuracy'),
    ]

    operations = [
        migrations.AlterField(
            model_name='lobby',
            name='startTime',
            field=models.DateTimeField(default=multi_mode.models.getStartTime),
        ),
    ]
